server:
  port: 9004
spring:
  rabbitmq:
    addresses: rabbitmq
  application:
    name: provider-service
eureka:
  client:
    service-url:
      defaultZone: http://urban-eurekaserver:8761/eureka
  instance:
    hostname: urban-admin
