server:
  port: 8999
eureka:
  client:
    service-url:
      defaultZone: http://urban-eurekaserver:8761/eureka
  instance:
    hostname: urban-apigateway
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**, /order/**, /publish/**, /requestProviders/**
        - id: provider-service
          uri: lb://provider-service
          predicates:
            - Path=/provider/**
